// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVg9RjciBV7DcJCB9Ja1urghTv-hFNOa0',
    appId: '1:183406678196:web:c2b88409308767c8ffc7e1',
    messagingSenderId: '183406678196',
    projectId: 'flutter-memo-app-5d75b',
    authDomain: 'flutter-memo-app-5d75b.firebaseapp.com',
    storageBucket: 'flutter-memo-app-5d75b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Fl8hD0Cm49-ZSNtwmXbc5f3Uu8hsIDw',
    appId: '1:183406678196:android:425e13d9bce9eb7bffc7e1',
    messagingSenderId: '183406678196',
    projectId: 'flutter-memo-app-5d75b',
    storageBucket: 'flutter-memo-app-5d75b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQqmNcVL1WXAqL1I5e_1lOYys5VzhuOsU',
    appId: '1:183406678196:ios:85c85306a6ca8e83ffc7e1',
    messagingSenderId: '183406678196',
    projectId: 'flutter-memo-app-5d75b',
    storageBucket: 'flutter-memo-app-5d75b.appspot.com',
    iosClientId: '183406678196-14n0i687f8ks2vh93kud41furbecd4dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fletterMemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQqmNcVL1WXAqL1I5e_1lOYys5VzhuOsU',
    appId: '1:183406678196:ios:85c85306a6ca8e83ffc7e1',
    messagingSenderId: '183406678196',
    projectId: 'flutter-memo-app-5d75b',
    storageBucket: 'flutter-memo-app-5d75b.appspot.com',
    iosClientId: '183406678196-14n0i687f8ks2vh93kud41furbecd4dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fletterMemo',
  );
}
